//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/PROJECT/Script/ActionMap/GameInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInputActions"",
    ""maps"": [
        {
            ""name"": ""CharacterSelection"",
            ""id"": ""7b1de464-319f-4558-9d9a-e0185970a6d6"",
            ""actions"": [
                {
                    ""name"": ""IncreaseCurrentCam"",
                    ""type"": ""Button"",
                    ""id"": ""45064ea3-c5e5-42ee-8ed6-b5c25450ccdd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DecreaseCurrentCam"",
                    ""type"": ""Button"",
                    ""id"": ""c47ae3f7-2619-4d17-abef-e7187730abf9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChooseCharacter"",
                    ""type"": ""Button"",
                    ""id"": ""bbf08758-f7fd-4531-8ea8-5e40f8ce66f7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1878080a-316f-4e41-9eab-dd5599d55f20"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IncreaseCurrentCam"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3efa055f-9689-4bd5-bf36-6520c6deb2b9"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DecreaseCurrentCam"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4cb8d361-f88f-4656-b37a-c6f8c108dd47"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChooseCharacter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CharacterSelection
        m_CharacterSelection = asset.FindActionMap("CharacterSelection", throwIfNotFound: true);
        m_CharacterSelection_IncreaseCurrentCam = m_CharacterSelection.FindAction("IncreaseCurrentCam", throwIfNotFound: true);
        m_CharacterSelection_DecreaseCurrentCam = m_CharacterSelection.FindAction("DecreaseCurrentCam", throwIfNotFound: true);
        m_CharacterSelection_ChooseCharacter = m_CharacterSelection.FindAction("ChooseCharacter", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CharacterSelection
    private readonly InputActionMap m_CharacterSelection;
    private ICharacterSelectionActions m_CharacterSelectionActionsCallbackInterface;
    private readonly InputAction m_CharacterSelection_IncreaseCurrentCam;
    private readonly InputAction m_CharacterSelection_DecreaseCurrentCam;
    private readonly InputAction m_CharacterSelection_ChooseCharacter;
    public struct CharacterSelectionActions
    {
        private @GameInputActions m_Wrapper;
        public CharacterSelectionActions(@GameInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @IncreaseCurrentCam => m_Wrapper.m_CharacterSelection_IncreaseCurrentCam;
        public InputAction @DecreaseCurrentCam => m_Wrapper.m_CharacterSelection_DecreaseCurrentCam;
        public InputAction @ChooseCharacter => m_Wrapper.m_CharacterSelection_ChooseCharacter;
        public InputActionMap Get() { return m_Wrapper.m_CharacterSelection; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CharacterSelectionActions set) { return set.Get(); }
        public void SetCallbacks(ICharacterSelectionActions instance)
        {
            if (m_Wrapper.m_CharacterSelectionActionsCallbackInterface != null)
            {
                @IncreaseCurrentCam.started -= m_Wrapper.m_CharacterSelectionActionsCallbackInterface.OnIncreaseCurrentCam;
                @IncreaseCurrentCam.performed -= m_Wrapper.m_CharacterSelectionActionsCallbackInterface.OnIncreaseCurrentCam;
                @IncreaseCurrentCam.canceled -= m_Wrapper.m_CharacterSelectionActionsCallbackInterface.OnIncreaseCurrentCam;
                @DecreaseCurrentCam.started -= m_Wrapper.m_CharacterSelectionActionsCallbackInterface.OnDecreaseCurrentCam;
                @DecreaseCurrentCam.performed -= m_Wrapper.m_CharacterSelectionActionsCallbackInterface.OnDecreaseCurrentCam;
                @DecreaseCurrentCam.canceled -= m_Wrapper.m_CharacterSelectionActionsCallbackInterface.OnDecreaseCurrentCam;
                @ChooseCharacter.started -= m_Wrapper.m_CharacterSelectionActionsCallbackInterface.OnChooseCharacter;
                @ChooseCharacter.performed -= m_Wrapper.m_CharacterSelectionActionsCallbackInterface.OnChooseCharacter;
                @ChooseCharacter.canceled -= m_Wrapper.m_CharacterSelectionActionsCallbackInterface.OnChooseCharacter;
            }
            m_Wrapper.m_CharacterSelectionActionsCallbackInterface = instance;
            if (instance != null)
            {
                @IncreaseCurrentCam.started += instance.OnIncreaseCurrentCam;
                @IncreaseCurrentCam.performed += instance.OnIncreaseCurrentCam;
                @IncreaseCurrentCam.canceled += instance.OnIncreaseCurrentCam;
                @DecreaseCurrentCam.started += instance.OnDecreaseCurrentCam;
                @DecreaseCurrentCam.performed += instance.OnDecreaseCurrentCam;
                @DecreaseCurrentCam.canceled += instance.OnDecreaseCurrentCam;
                @ChooseCharacter.started += instance.OnChooseCharacter;
                @ChooseCharacter.performed += instance.OnChooseCharacter;
                @ChooseCharacter.canceled += instance.OnChooseCharacter;
            }
        }
    }
    public CharacterSelectionActions @CharacterSelection => new CharacterSelectionActions(this);
    public interface ICharacterSelectionActions
    {
        void OnIncreaseCurrentCam(InputAction.CallbackContext context);
        void OnDecreaseCurrentCam(InputAction.CallbackContext context);
        void OnChooseCharacter(InputAction.CallbackContext context);
    }
}
